services:
  fast:
    build:
      context: ./fastapi
      # fastapi의 Dockerfile경로
    image: fast-img:1
    
  svel: 
    build:
      context: ./svelte
    image: svel-img:1
    ports:
    - '80:80'
